name: reliamol3d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24
  - pandas>=2.0
  - scipy>=1.10
  - scikit-learn>=1.3
  - pyyaml>=6.0
  - tqdm>=4.66
  - rdkit>=2023.09
  - pytorch>=2.1
  - pip
  - pip:
      - posebusters
